# Test the code on push

name: Test and upload code coverage

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # Install requirements
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: show python path
        run: |
          python -c "import sys; print('\n'.join(sys.path))"

      # Run tests
      - name: Run tests
        run: |
          pip install pytest pytest-cov
          python -m pytest --cov=mlforge tests/

      # Upload coverage reports to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: renero/mlforge
